### ISSUE TITLE
Limit Switch Interface

### ISSUE THREAD

**Issue by mikeshams** [ShivinderK/Capstone_Project#5]
What issues did you face? How to resolve?

**Comment by RaghavChopra95** [comment]
1. In the code I added the delay function but while running the code it was giving error. So I checked it I realized that it requires specific libraries for delay function, so I added the unistd.h library in the code and then I got rid of that error.
2. I made my code with if else statement but there were some errors in that so I improvise the code by using this link https://www.programiz.com/c-programming/c-if-else-statement; this helped me to know how we can properly use the if else statement. 
3. While running the code LEDs were not glowing when I was pushing the button of limit switch but was getting output on the terminal. Then I realized that I have used the resistor of high value which was 1K so I changed it to 220 ohm. After that LEDs started glowing too.
