### ISSUE TITLE
Plug & Play Mode

### ISSUE THREAD

**Issue by mikeshams** [ShivinderK/Capstone_Project#8]
How did you make your project in plug and play mode? Explain about the steps you have taken here!

**Comment by 1511992** [comment]
Plug and Play Mode: Plug and play mode is the mode when the user does not have to install or run manually. The hardware and software  setting is done in such a way that there is no need of external USB Cable for the main microcontroller to run the whole project. Instead, only a power adapter is required to give the supply to the project. In our project, we are powering the whole project by a power adapter directly connect to power socket and our main microcontroller i.e. Beaglebone Black to run the project automatically. When the project will run it will sound a beep after few seconds, which ensures the system is ready to use.

The steps to make the project autorun are as follows:

1.Find the location of object file of Garagedoor using command pwd
2. We get location as home/debian/GarageDoor
3. Run command - sudo nano /lib/systemd/system/autostart.service
4. Add this to nano terminal --scripted file for autorun
[Unit]
 Description=Service File to start the GarageDoor File
After=syslog.target network.target
[Service]
Type=simple
ExecStart=/home/debian/GarageDoor
[Install]
WantedBy=user.target



Ctrl+o   enter ctrl+X


5. run command- sudo systemctl enable autostart.service

6. Sudo reboot

Reference: https://stackoverflow.com/questions/28854705/executing-a-script-on-startup-using-beaglebone-black
